env:
  es6: true
  browser: true
  commonjs: true

extends: [
  'htmlacademy/es6',
  'plugin:react/recommended',
  ]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react', '@typescript-eslint']

settings:
  react:
    version: '16'

parser: '@typescript-eslint/parser'

