env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: [
  'htmlacademy/es6',
  'plugin:react/recommended',
  'plugin:@typescript-eslint/recommended',
  ]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react', '@typescript-eslint']

settings:
  react:
    version: '16'

parser: '@typescript-eslint/parser'

rules: {
  '@typescript-eslint/no-empty-function': 'off',
  '@typescript-eslint/explicit-function-return-type': 'off',
  'react/prop-types': 'off'
 }
